import { prisma } from "@/lib/prisma";
import { saveResourceType } from "../actions";

export const dynamic = "force-dynamic";

export default async function ResourceTypesPage() {
  const types = await prisma.resourceType.findMany({ include: { _count: { select: { resources: true } } }, orderBy: [{ displayOrder: "asc" }, { name: "asc" }] });
  return <main className="admin-main"><div className="admin-page-heading"><div><p>Resources</p><h1>Resource types</h1><span>Create categories that keep the resource library organized.</span></div></div><section className="admin-panel admin-create-panel"><div><span>New type</span><h2>Add a resource type</h2></div><form className="admin-inline-create" action={saveResourceType}><label>Name *<input name="name" required /></label><label>Slug<input name="slug" placeholder="Generated from name" /></label><label>Description<input name="description" /></label><label>Order<input type="number" name="displayOrder" defaultValue="0" /></label><input type="hidden" name="status" value="active" /><button>Add type</button></form></section><section className="admin-stack">{types.length === 0 ? <div className="admin-empty"><h2>No resource types yet</h2></div> : types.map((type) => <details className="admin-edit-card" key={type.id}><summary><div><strong>{type.name}</strong><small>{type.slug} · {type._count.resources} resources</small></div><span className={`admin-status status-${type.status}`}>{type.status}</span><b>Edit</b></summary><form className="admin-inline-create" action={saveResourceType}><input type="hidden" name="id" value={type.id} /><label>Name *<input name="name" defaultValue={type.name} required /></label><label>Slug<input name="slug" defaultValue={type.slug} /></label><label>Description<input name="description" defaultValue={type.description ?? ""} /></label><label>Order<input type="number" name="displayOrder" defaultValue={type.displayOrder} /></label><label>Status<select name="status" defaultValue={type.status}><option value="active">Active</option><option value="archived">Archived</option></select></label><button>Save changes</button></form></details>)}</section></main>;
}
