import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { addApplicationNote, updateApplicationStatus } from "../../actions";

export const dynamic = "force-dynamic";

function Row({ label, value, href }: { label: string; value?: string | number | null; href?: string }) { if (value === null || value === undefined || value === "") return null; return <div><dt>{label}</dt><dd>{href ? <a href={href}>{value}</a> : value}</dd></div>; }

export default async function ApplicationDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const application = await prisma.application.findUnique({ where: { id }, include: { job: true, notes: { orderBy: { createdAt: "desc" } } } });
  if (!application) notFound();
  const statuses = ["unread", "reviewing", "shortlisted", "interview", "rejected", "hired", "archived"];
  return <main className="admin-main"><div className="admin-page-heading"><div><p><Link href="/admin/applications">Applications</Link> / Candidate</p><h1>{application.firstName} {application.lastName}</h1><span>{application.jobTitleSnapshot} · Received {application.receivedAt.toLocaleString("en-US")}</span></div><a className="admin-primary" href={`mailto:${application.email}`}>Contact applicant</a></div><div className="admin-detail-layout"><section className="admin-panel"><div className="admin-panel-heading"><div><span>Application</span><h2>Candidate details</h2></div><form className="admin-inline-form" action={updateApplicationStatus}><input type="hidden" name="id" value={application.id} /><select name="status" defaultValue={application.status}>{statuses.map((status) => <option key={status}>{status}</option>)}</select><button>Update</button></form></div><dl className="admin-detail-list"><Row label="Email" value={application.email} href={`mailto:${application.email}`} /><Row label="Phone" value={application.phone} href={application.phone ? `tel:${application.phone}` : undefined} /><Row label="Position" value={application.jobTitleSnapshot} /><Row label="Address" value={application.fullAddress} /><Row label="Portfolio" value={application.portfolio} href={application.portfolio?.startsWith("http") ? application.portfolio : undefined} /><Row label="Message" value={application.message} /><Row label="Internet provider" value={application.internetProvider} /><Row label="Download speed" value={application.downloadSpeed ? `${application.downloadSpeed} Mbps` : null} /><Row label="Upload speed" value={application.uploadSpeed ? `${application.uploadSpeed} Mbps` : null} /><Row label="Secure location" value={application.secureLocation} /><Row label="Availability" value={application.availability} /><Row label="Résumé filename" value={application.resumeOriginalName} /><Row label="Consent" value={`${application.consentVersion} · ${application.consentedAt.toLocaleString("en-US")}`} /><Row label="Application ID" value={application.id} /></dl></section><aside className="admin-panel admin-notes"><div className="admin-panel-heading"><div><span>Private</span><h2>Internal notes</h2></div></div><form action={addApplicationNote}><input type="hidden" name="applicationId" value={application.id} /><label>Add a note<textarea name="body" rows={4} maxLength={3000} required /></label><button>Add note</button></form><div className="admin-note-list">{application.notes.length === 0 ? <p>No notes yet.</p> : application.notes.map((note) => <article key={note.id}><p>{note.body}</p><small>{note.createdBy} · {note.createdAt.toLocaleString("en-US")}</small></article>)}</div></aside></div></main>;
}
