import Link from "next/link";
import { saveResource } from "../actions";

type TypeOption = { id: string; name: string };
type ResourceValue = { id?: string; resourceTypeId?: string; title?: string; slug?: string; summary?: string; body?: string; externalUrl?: string | null; coverImageUrl?: string | null; status?: string; displayOrder?: number };

export default function ResourceForm({ types, resource }: { types: TypeOption[]; resource?: ResourceValue }) {
  return <form className="admin-form" action={saveResource}>{resource?.id && <input type="hidden" name="id" value={resource.id} />}<div className="admin-form-section"><div><span>Resource</span><h2>Content</h2></div><div className="admin-fields"><label>Title *<input name="title" defaultValue={resource?.title} required /></label><div className="admin-field-row"><label>Slug<input name="slug" defaultValue={resource?.slug} placeholder="Generated from title" /></label><label>Resource type *<select name="resourceTypeId" defaultValue={resource?.resourceTypeId ?? ""} required><option value="" disabled>Select a type</option>{types.map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select></label></div><label>Short summary *<textarea name="summary" rows={3} defaultValue={resource?.summary} required /></label><label>Body *<textarea name="body" rows={10} defaultValue={resource?.body} required /></label></div></div><div className="admin-form-section"><div><span>Publishing</span><h2>Links &amp; status</h2></div><div className="admin-fields"><label>External URL<input type="url" name="externalUrl" defaultValue={resource?.externalUrl ?? ""} placeholder="https://" /></label><label>Cover image URL<input type="url" name="coverImageUrl" defaultValue={resource?.coverImageUrl ?? ""} placeholder="https://" /></label><div className="admin-field-row"><label>Status<select name="status" defaultValue={resource?.status ?? "draft"}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Display order<input type="number" name="displayOrder" defaultValue={resource?.displayOrder ?? 0} /></label></div></div></div><div className="admin-form-actions"><Link href="/admin/resources">Cancel</Link><button>{resource?.id ? "Save changes" : "Create resource"}</button></div></form>;
}
